### ISSUE TITLE
how do i set this up

### ISSUE THREAD

**Issue by chaoibi** [headshot2017/sm64-san-andreas#10]
how the hell do i set this up i do not understand everything i've tried it just didnt apply to the game at all

**Comment by stonedDiscord** [comment]
Go to the [Actions](https://github.com/headshot2017/sm64-san-andreas/actions) page
    Click the first item that appears in the "workflow runs" list
    Scroll down to "Artifacts" and click "sm64-san-andreas-release"
    Extract the zip's contents to your GTA SA "scripts" folder.

**Comment by chaoibi** [comment]
> 

thanks alot for the help
