### ISSUE TITLE
if i press M nothing happens

### ISSUE THREAD

**Issue by whateverlior** [headshot2017/sm64-san-andreas#11]
so i did everything correctly and i hear the star sound when starting the game but pressing m does nothing

**Comment by headshot2017** [comment]
did you do the compiling tutorial or download from github actions?

**Comment by whateverlior** [comment]
> did you do the compiling tutorial or download from github actions?

i downloaded it from the actions

**Comment by headshot2017** [comment]
where are you pressing M? in the main menu or ingame?

**Comment by whateverlior** [comment]
ingame

**Comment by whateverlior** [comment]
are you still there?

**Comment by whateverlior** [comment]
nevermind... i had a modded installation and now i have a clean one and applied it, it works now
