### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Alopez55** [headshot2017/sm64-san-andreas#14]
Yeah I can't figure this out, I'd appreciate some help. You can contact me on Discord. My user is alopez5. I'd really appreciate the help! Thanks!

**Comment by headshot2017** [comment]
are you following the "compiling" instructions or the github actions download instructions?

**Comment by Alopez55** [comment]
I am, and I think the files are in place but when I open up the game nothing happens.

**Comment by Alopez55** [comment]
like what versions of the game does this mod work with exactly? that could be my issue here

**Comment by headshot2017** [comment]
only v1.0
if you're on the delisted steam version you need to use the downgrader tool

**Comment by Alopez55** [comment]
does it not work for the newer version, the one thats in the bundle or whatever

**Comment by headshot2017** [comment]
no, you need to use the downgrader tool to bring the game down to v1.0

**Comment by Alopez55** [comment]
no i meant like the one thats part of the bundle the deluxe
 version

**Comment by headshot2017** [comment]
what bundle? deluxe version? where did you get the game from?

**Comment by headshot2017** [comment]
that's the definitive edition, this mod does not work with that, you need the original version

**Comment by headshot2017** [comment]
i think you can buy it from rockstar's website (not the launcher), it's been delisted from steam, idk where else though

**Comment by Alopez55** [comment]
yeah i just checked

**Comment by Alopez55** [comment]
dang bro that sucks

**Comment by headshot2017** [comment]
[the trilogy is available here on rockstar](https://store.rockstargames.com/game/buy-grand-theft-auto-the-trilogy) 

check out [this post on reddit](https://www.reddit.com/r/GTA/comments/139u80e/how_can_i_buy_gta_san_andreas_2005_for_pc/) as well

**Comment by Alopez55** [comment]
wait so the trilogy is just the original games right?

**Comment by headshot2017** [comment]
from what i read in the reddit post, yeah, it appears to be

i didn't check further though so it might be wrong

**Comment by Alopez55** [comment]
ill try it out

**Comment by Alopez55** [comment]
i think it is

**Comment by Alopez55** [comment]
hi so yes it is the original so thank you for that but i still had a few other questions
do i still downgrade it even though its not steam
where do i put the rom?
and do i create a scripts folder on the main area or in the data folder

**Comment by headshot2017** [comment]
yes, run the downgrader

put the rom in the same folder as the gta_sa.exe, with the file name "sm64.us" (or "sm64.us.z64" if you have file extensions unhidden)

create a scripts folder in the main area, where the gta sa exe is

**Comment by Alopez55** [comment]
ok so the downgrader doesnt seem to work

**Comment by Alopez55** [comment]
yeah idk how to go back to 1.0 with rockstar

**Comment by Alopez55** [comment]
because i did everything else

**Comment by headshot2017** [comment]
you're sure that you're pointing the downgrader to the trilogy one and not the definitive edition?

**Comment by Alopez55** [comment]
yes i am

**Comment by Alopez55** [comment]
there is

**Comment by Alopez55** [comment]
do i just verify then downgrade again?

**Comment by headshot2017** [comment]
revert downgrade, verify, and downgrade

**Comment by Alopez55** [comment]
Yeah no dice still having the same issues

**Comment by Alopez55** [comment]
I think I’m just gonna give up honestly. This is too much work lol. Cool mod but it’s really hard to set up for small brain people like myself. But thanks anyways man.
