### ISSUE TITLE
Correctly Named (US) ROMs Don't Work

### ISSUE THREAD

**Issue by TheRealSkarlax** [headshot2017/sm64-san-andreas#15]
I've tried the ROM I already have, and I've tried downloading other USA ROMs from other sites. Despite the correct file name, it comes up with the error below when I start the game.
I've copy/pasted the ROM into my Grand Theft Auto San Andreas file, alongside the executable, and it doesn't work.
Any idea what the issue with this is?

![image](https://github.com/headshot2017/sm64-san-andreas/assets/146075620/722337f0-8683-49b2-902a-06955c223d6e)

**Comment by headshot2017** [comment]
try naming the file "sm64.us" instead, you may have file extensions hidden

**Comment by TheRealSkarlax** [comment]
I've had extensions showing.

**Comment by headshot2017** [comment]
send a screenshot of your entire gta sa folder so i can ascertain what is happening

**Comment by TheRealSkarlax** [comment]
![image](https://github.com/headshot2017/sm64-san-andreas/assets/146075620/a853d7ab-c0a3-44d6-8fd1-7118784c7b8d)

**Comment by headshot2017** [comment]
try opening both gta sa exes on that folder to see if it works

**Comment by TheRealSkarlax** [comment]
I get the same error on both exes.
![gta-sa](https://github.com/headshot2017/sm64-san-andreas/assets/146075620/2cefb8f9-eb9e-48a0-a01c-a79365792290)
![gta_sa](https://github.com/headshot2017/sm64-san-andreas/assets/146075620/a09ee8ee-0e2a-44a1-9072-b6314886d68d)

**Comment by TheRealSkarlax** [comment]
So I've got ASI Modloader. The .asi goes into the modloader folder, right? 'Cause that's where I have it.

**Comment by headshot2017** [comment]
the sm64-san-andreas asi and the included DLL files are meant to go in the scripts folder, although i don't think it makes a difference

**Comment by TheRealSkarlax** [comment]
I'll give that a shot, just in case.

**Comment by TheRealSkarlax** [comment]
Oh my god, it worked. LMAO

**Comment by headshot2017** [comment]
well that's a relief

**Comment by TheRealSkarlax** [comment]
Absolutely. lol
Thanks for your help!
