### ISSUE TITLE
mario doesnt have sounds

### ISSUE THREAD

**Issue by gg676** [headshot2017/sm64-san-andreas#17]
ok so after putting mario64 on gta san andreas it worked but then i decided to add another mod and that mod caused mario to have no sound i dont hear the sound when hes walking or when hes going wahooo and all of that headshot do u know how to fix this?

**Comment by headshot2017** [comment]
what is the other mod you installed?

**Comment by gg676** [comment]
it was some mod that i installed idk i think it was like a mod that when u die the like gta 5 screen shows up and that ruined it i think  the reason why i downloaded this its cuz it looks kinda cool for me

**Comment by gg676** [comment]
and the notepad didnt fix it for some reason

**Comment by headshot2017** [comment]
> it was some mod that i installed idk i think it was like a mod that when u die the like gta 5 screen shows up and that ruined it i think  the reason why i downloaded this its cuz it looks kinda cool for me

i need the mod name so i can test this myself and see what's going on

**Comment by gg676** [comment]
here it is https://www.gtainside.com/en/sanandreas/mods/126973-gta-5-wasted-and-busted-screen-in-sa/

**Comment by headshot2017** [comment]
try removing that mod and starting the game with only the sm64 mod

**Comment by gg676** [comment]
i did

**Comment by gg676** [comment]
but it still doesnt work

**Comment by gg676** [comment]
u know any other method

**Comment by gg676** [comment]
what do i do run as administrator or choose another compatibility

**Comment by headshot2017** [comment]
can you show me screenshots of your gta sa folder and the scripts folder?

**Comment by gg676** [comment]
whats ur discord

**Comment by headshot2017** [comment]
you can post images here

**Comment by gg676** [comment]
ok wait

**Comment by gg676** [comment]
![Screenshot_1](https://github.com/headshot2017/sm64-san-andreas/assets/152508584/d15b67db-04d8-402b-b210-f107e017eafa)

**Comment by gg676** [comment]
![Screenshot_2](https://github.com/headshot2017/sm64-san-andreas/assets/152508584/e1fb3876-8dff-4f13-af99-7fe927417aa8)

**Comment by gg676** [comment]
![Screenshot_3](https://github.com/headshot2017/sm64-san-andreas/assets/152508584/ab3b6803-47db-4bbd-9b7b-8ac84d4cc97f)
what do i do

**Comment by stonedDiscord** [comment]
do you have dialog sound when story characters or pedestrians talk?

**Comment by gg676** [comment]
idk

**Comment by stonedDiscord** [comment]
then fix that first, often you have to set your sound card from 5.1 audio to stereo
https://steamcommunity.com/app/12120/discussions/0/41973820589033630/

**Comment by baldi2** [comment]
was fixed?

**Comment by SANTIQDCO** [comment]
how do i fix it mine is not from git hub

**Comment by dave41413** [comment]
was fixed?

**Comment by stonedDiscord** [comment]
It was working the entire time
