### ISSUE TITLE
SkyGFX Dual Pass Compatibility 

### ISSUE THREAD

**Issue by SplatJam** [headshot2017/sm64-san-andreas#19]
When I play with SkyGFX with the "Dual Pass " toggle enabled, one of two things will happen. Either the game will flat out crash after pressing "M" or Mario will load in properly, but his textures don't display properly. The textures do display normally after disabling the toggle.

![image](https://github.com/headshot2017/sm64-san-andreas/assets/138066583/38c94d63-0b2a-4d00-8f5b-ada0ee6d9bb5)

A fix for this would  be nice, but its not necessary because having the toggle disabled allows both mods to work properly.

![image](https://github.com/headshot2017/sm64-san-andreas/assets/138066583/4916a845-e35e-4ba1-abb0-ea149860ba8d)

**Comment by headshot2017** [comment]
this is on the Known issues section in the readme. if there's a way i could detect skygfx and disable dualpass through this mod, i'd do that

**Comment by SplatJam** [comment]
I apologize, I only just saw the issue today.

> this is on the Known issues section in the readme. if there's a way i could detect skygfx and disable dualpass through this mod, i'd do that
