### ISSUE TITLE
Error Super mario 64 us rom not found 

### ISSUE THREAD

**Issue by 171103** [headshot2017/sm64-san-andreas#25]
I'm getting this even tho i have the game and the name right so if anyone can help me and yes i'm on version 1,0

![hghf](https://github.com/headshot2017/sm64-san-andreas/assets/166035872/e526617b-fd6a-4f30-88a1-f67763e9fe07)

**Comment by headshot2017** [comment]
you have file extensions hidden. you must rename it to "sm64.us"

**Comment by 171103** [comment]
Omg thank you very much i was legit doing this for ovr 2 hours and nothing worked thank you xD

**Comment by headshot2017** [comment]
nice
