### ISSUE TITLE
How do i run it?

### ISSUE THREAD

**Issue by SANTIQDCO** [headshot2017/sm64-san-andreas#27]
i think is with emulator or something,but , how to i run it?

**Comment by SANTIQDCO** [comment]
![sm64-san-andreas-master 09_07_2024 3_09_38](https://github.com/headshot2017/sm64-san-andreas/assets/164812142/8a94f82a-e97b-4492-ba18-71b84989f522)

**Comment by headshot2017** [comment]
no. this is a mod for the PC version of GTA San Andreas. it's not an SM64 rom hack. you need to install GTA SA on your PC, and look at the readme on the project's main page on how to install it

**Comment by SANTIQDCO** [comment]
i know is not an sm64 hack but idk how do i install it and wheres the readme :(

**Comment by headshot2017** [comment]
first install gta sa

[https://github.com/headshot2017/sm64-san-andreas](https://github.com/headshot2017/sm64-san-andreas)

scroll down and there's the readme

download these and put them on your gta sa folder:

> This plugin requires the following in order to work:
> * [Silent's ASI Loader](https://www.gtagarage.com/mods/show.php?id=21709)
> * Super Mario 64 US ROM, with the filename `sm64.us.z64`, located in the GTA San Andreas folder alongside `gta_sa.exe`

then download the mod:

> ## How to download
> **This requires you to be logged in to your GitHub account.**
> * Go to the [Actions](https://github.com/headshot2017/sm64-san-andreas/actions) page
> * Click the first item that appears in the "workflow runs" list
> * Scroll down to "Artifacts" and click "sm64-san-andreas-release"
> * Extract the zip's contents to your GTA SA "scripts" folder.

this is all in the readme

**Comment by SANTIQDCO** [comment]
close
