### ISSUE TITLE
No errors during compilation, game refuses to start

### ISSUE THREAD

**Issue by GANONdork123** [headshot2017/sm64-san-andreas#4]
I followed the compilation tutorial and it looks as though everything is correct. Everything compiled with 0 errors and the game executes normally using SilentPatch. using the compiled script however, the game simply doesn't start, showing up in Task Manager as a background task using about 10% of my CPU and 6MB of RAM. I attempted compiling all 3 projects as Debug as well, but the result is the same. I am using a downgraded 1.0 version of the game. I've made sure my SM64 ROM file has the correct name as well. SHA1 hash for the ROM file is 9bef1128717f958171a4afac3ed78ee2bb4e86ce

**Comment by headshot2017** [comment]
what is your OS? also maybe try launching the game twice to see if the 2nd instance does run, it happens on my win7 vm

**Comment by GANONdork123** [comment]
It seems the version of the game I was running was not the 1.0 version. I was under the impression the backup of the game files I was using for this was not downgraded before backing it up. After doing the downgrade the game boots and I hear the SM64 warp sound upon startup.

**Comment by GANONdork123** [comment]
Now I just need to figure out how to switch to Mario.

**Comment by headshot2017** [comment]
M key
