### ISSUE TITLE
I have Problem

### ISSUE THREAD

**Issue by IslamMachido** [headshot2017/sm64-san-andreas#5]
When pressed generate, the plugin file doesn't show

**Comment by headshot2017** [comment]
> To create the Code::Blocks Plugin-SDK workspace, replace tools\premake\premake5.exe with [this version](https://github.com/DK22Pac/plugin-sdk/raw/cc130098120f45de0f62f34681555d7184719263/tools/premake/premake5.exe), otherwise it won't work

it sounds like you missed this part in the wiki tutorial page

**Comment by IslamMachido** [comment]
Thanks you much to helping me it work.
