### ISSUE TITLE
Game crash when opening

### ISSUE THREAD

**Issue by inkatail** [headshot2017/sm64-san-andreas#7]
Crash when trying to run the game, what can be the issue?
I did everything good and i have the asi loader and silent patch installed, and the rom in gta sa directory.

**Comment by headshot2017** [comment]
are you trying to run `gta-sa.exe` or `gta_sa.exe`? note whether it has a minus sign or the underscore symbol, as the one with the minus sign is the Steam version of the game.

this mod doesn't work with the Steam version - you need to use the San Andreas Downgrader tool if you haven't before

**Comment by inkatail** [comment]
gta_sa.exe

**Comment by inkatail** [comment]
But i think i fixed it by getting an different rom from r/roms megathread.
Idk why the vimm's lair rom didnt want to work

**Comment by inkatail** [comment]
Sorry for wasting your time or smh

**Comment by headshot2017** [comment]
oh
